# Generated by Django 5.2.14 on 2026-06-01 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pickup_code',
            field=models.PositiveIntegerField(default=0, verbose_name='Код получения'),
        ),
    ]
